### ISSUE TITLE
OT: soundtrack

### ISSUE THREAD

**Issue by Zibri** [ZgzInfinity/OutRun#31]
Nice work!
Just a hint: this is the best arrangements of one of the original tracks (not done by me):
it would be a nice option...
https://soundcloud.com/zibri/outrun-passing-breeze-lounge

**Comment by ZgzInfinity** [comment]
I have listen it, the song is amazing but i don`t think that this kind of song match with the theme o the game. The rhythm is slow and relaxed and it should be a bit more retro because there is a lot of contrast. For any contribution do not forget to tell us
