### ISSUE TITLE
Compile fails with error: "Input.h:127:63: error: field 'resolutions' has incomplete type "

### ISSUE THREAD

**Issue by ghost** [ZgzInfinity/OutRun#32]
I set up a project in codeblocks and wanted to compile the master branch on my Linux box. But I get the error I pasted below. 

My gcc version is: gcc (GCC) 12.2.0

-------------- Build: Debug in OutRun (compiler: GNU GCC Compiler)---------------

Skipping file (no compiler program set): ../../../src/OutRun/Resources/resource.rc
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Audio/Audio.cpp -o obj/Debug/src/OutRun/src/Audio/Audio.o
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Car/PlayerCar/PlayerCar.cpp -o obj/Debug/src/OutRun/src/Car/PlayerCar/PlayerCar.o
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Car/TrafficCar/TrafficCar.cpp -o obj/Debug/src/OutRun/src/Car/TrafficCar/TrafficCar.o
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Car/Vehicle/Vehicle.cpp -o obj/Debug/src/OutRun/src/Car/Vehicle/Vehicle.o
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Game/Game.cpp -o obj/Debug/src/OutRun/src/Game/Game.o
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Gui/Button/Button.cpp -o obj/Debug/src/OutRun/src/Gui/Button/Button.o
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Gui/Huds/HudBonus/HudBonus.cpp -o obj/Debug/src/OutRun/src/Gui/Huds/HudBonus/HudBonus.o
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Gui/Huds/HudCheckPoint/HudCheckPoint.cpp -o obj/Debug/src/OutRun/src/Gui/Huds/HudCheckPoint/HudCheckPoint.o
/home/nhaede/src/OutRun/src/Car/PlayerCar/PlayerCar.cpp:26:9: warning: #pragma once in main file
   26 | #pragma once
      |         ^~~~
/home/nhaede/src/OutRun/src/Gui/Button/Button.cpp: In member function 'void Button::setButtonState(const ButtonState&)':
/home/nhaede/src/OutRun/src/Gui/Button/Button.cpp:86:12: warning: enumeration value '__COUNT' not handled in switch [-Wswitch]
   86 |     switch (state) {
      |            ^
g++ -Wall -g -std=c++14  -c /home/nhaede/src/OutRun/src/Gui/Huds/HudRound/HudRound.cpp -o obj/Debug/src/OutRun/src/Gui/Huds/HudRound/HudRound.o
In file included from /home/nhaede/src/OutRun/src/Audio/Audio.h:36,
                 from /home/nhaede/src/OutRun/src/Audio/Audio.cpp:26:
/home/nhaede/src/OutRun/src/Audio/../Input/Input.h:127:63: error: field 'resolutions' has incomplete type 'std::array<std::pair<int, int>, 4>'
  127 |     std::array<std::pair<int, int>, (int)Resolution::__COUNT> resolutions;
      |                                                               ^~~~~~~~~~~
In file included from /usr/include/c++/12.2/mutex:38,
                 from /home/nhaede/src/OutRun/src/Audio/Audio.h:33:
/usr/include/c++/12.2/tuple:1595:45: note: declaration of 'struct std::array<std::pair<int, int>, 4>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
/home/nhaede/src/OutRun/src/Audio/Audio.h:171:74: error: field 'themes' has incomplete type 'std::array<std::unique_ptr<sf::Music>, 16>'
  171 |         std::array<std::unique_ptr<sf::Music>, (int)Soundtrack::__COUNT> themes;
      |                                                                          ^~~~~~
/usr/include/c++/12.2/tuple:1595:45: note: declaration of 'struct std::array<std::unique_ptr<sf::Music>, 16>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
/home/nhaede/src/OutRun/src/Audio/Audio.h:174:67: error: field 'effects' has incomplete type 'std::array<std::unique_ptr<sf::Music>, 66>'
  174 |         std::array<std::unique_ptr<sf::Music>, (int)Sfx::__COUNT> effects;
      |                                                                   ^~~~~~~
/usr/include/c++/12.2/tuple:1595:45: note: declaration of 'struct std::array<std::unique_ptr<sf::Music>, 66>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
Process terminated with status 1 (0 minute(s), 1 second(s))

**Comment by ZgzInfinity** [comment]
The truth is that it is a bit strange. Note that you have the same error several times. 

Do you have SFML configured correctly? If so, maybe the problem is related to the standard you use, I see that it is C++14, but it may not be catching it well. Try to put just in case #include<array> in the files where you get the error. 

My version of Codeblocks is 17.12. First check that SFML is well referenced and then add the other. By the way, the project uses the thread support library. Make sure you use the pthread compile flag.

**Comment by ghost** [comment]
Fixed it myself: compiling the code with gcc / g++ 6.x works! I just had a too recent version of gcc / g++ installed.
